bigquery:
  project_id: 'mlchatagent-429005'
  dataset_id: 'telecom_churn'
  region: 'us-central1'
sql_run:
  call_await: False
  num_table_matches : 3
  num_column_matches : 10
  table_similarity_threshold : 0.3
  column_similarity_threshold : 0.7 
  example_similarity_threshold : 0.7 
  num_sql_matches: 3
  DEBUGGING_ROUNDS : 5
  RUN_DEBUGGER : True 
  LLM_VALIDATION: True
  EXECUTE_FINAL_SQL : True
  VECTOR_STORE: bigquery-vector
  DATA_SOURCE: bigquery
  KGQ_ENABLED: True  
