import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import io
import base64
from abc import ABC
import vertexai
from vertexai.language_models import TextGenerationModel
from vertexai.language_models import CodeGenerationModel
from vertexai.language_models import CodeChatModel
from vertexai.generative_models import GenerativeModel
from vertexai.generative_models import HarmCategory,HarmBlockThreshold
from vertexai.generative_models import GenerationConfig
from vertexai.language_models import TextEmbeddingModel
import time
import json
from google.cloud import bigquery
from google.cloud import bigquery_connection_v1 as bq_connection
import pandas as pd
from datetime import datetime
import google.auth
import pandas as pd
import yaml
from google.cloud.exceptions import NotFound
import google.generativeai as genai

with open('./llm_configs.yml') as file:
    conf = yaml.load(file, Loader=yaml.FullLoader)

class ShapOracle(ABC):
    """ 
    This agent creates report from SHAP contribution data

    Attributes
    ----------
    agentType : str
        The type of agent.
    churnexplainer : genai.GenerativeModel
        The generative model used to splits the task to subtasks.

    Methods
    -------
    ask_churnoracle(shap_summary):
        Generates subtasks based on the user's question.
    """

    agentType = "ShapOracle"

    def __init__(self,config_file="./conf_telchurn.yml"):
        """
        Constructs all the necessary attributes for the TaskMaster object.
        """


        self.churnexplainer = genai.GenerativeModel(model_name="gemini-1.5-flash-001")
        with open(config_file) as file:
            self.conf = yaml.load(file, Loader=yaml.FullLoader)
    def ask_churnoracle(self,user_question, shap_summary: str) -> dict:
        """
        Generates a report on reasons for churn from shap summary.

        Parameters
        ----------
        shap_summary : str
            shap summary.
        user_question : str
            user's question.
        features : list
            The features of the data.

        Returns
        -------
        dict
            A report on reasons for churn.
        """
        prompt = conf['churn_oracle']['prompt0']+f"""

            Below is the SHAP summary data you need to analyze:
            {shap_summary}

            Below is the original user question. Use it to identify the context of the report:
            {user_question}
                         
            """
        prompt = prompt+ conf['churn_oracle']['prompt1']
        shap_action = self.churnexplainer.generate_content(prompt, stream=False)
        return shap_action.candidates[0].content.parts[0].text
    
    def ask_recommendation(self,user_question:str, counterfactual: str,customer:str) -> dict:
        """
        Generates a report on recommended actions to reduce churn for a customer.

        Parameters
        ----------
        shap_summary : str
            shap summary.
        user_question : str
            user's question.
        features : list
            The features of the data.

        Returns
        -------
        str
            A report on recommended actions to reduce churn for a customer. 
        """
        if ((not counterfactual) or (len(counterfactual.strip()) > 100)):

            prompt = f"""

                You are an assistant to customer service manager who is looking for recommendations to reduce churn for a specific customer.
                You have access to recommended actions to prevent churn generated by counterfactual analysis of action features for a specific customer.
                Your goal is to provide clear and actionable insights on how to reduce customer churn based on counterfactual analysis and to develop effective questions to engage customers and implement the recommendations.
                Your task is as below:-

                    1. Read and Analyze the Data:
                        - Understand the counterfactual recommendations for the specific customer.
                        - Understand who the customer is. Focus on customer and contract features.
                            Below is the list of customer level feature names:
                            {self.conf['llm_subsets']['customer_features']}
                            Below is the list of customer contract feature names:
                            {self.conf['llm_subsets']['contract_features']}

                    2. Identify Key Insights:
                        - There might be multiple recommendations for the customer. 
                        - Use the rank of the recommendations to prioritize the actions order
                        - If multiple recommendations contains same actions with minor changes, consider only the top ranked action.
                        - If possible specify the churn probability reduced by each successful action. Keep the probability change in percentage scale and rounded to 2 decimal places.
                        - Understand what the current values of the customer are for the features in the recommendations.

                    3. Communicate Clearly:
                        - Use simple and clear language to explain the recommendations.
                        - Avoid technical jargon and ensure the explanation is understandable for a customer service agent.

                    4. Provide Specific Recommendations:
                        - Detail the actions that can be taken to reduce churn.
                        - Explain why these actions are effective based on the counterfactual analysis.
                        - Include examples or scenarios to illustrate the recommendations.

                    5. Create Questionnaires:
                        - Develop specific questions for customer service agents to ask customers in order to implement the recommended actions.
                        - Ensure the questions are relevant to the recommended actions and designed to gather necessary information or prompt customer engagement.
                        - Do not ask personal questions or questions about data already available to you.
                        - Questionnaire should be sequenced in a way that it helps to implement the recommendations.
                        - QUestionnaire should be designed in a way that it helps to understand the customer's current situation and how the recommendations can be implemented.
                        - Questionnaire should be sequential. The answer to one question should lead to the next question.
                        - Create multiple different segments of questions for each recommended action.


                Below is the counterfactual recommendations for the specific customer:
                {counterfactual}

                Below is the customer details:
                {customer}

                Below is the original user question. Use it to identify the context of the report:
                {user_question}


                ***OUTPUT FORMAT SHOULD BE AS BELOW***:

                1. Customer Persona::
                    - Describe who the customer is in 30 words or less, including a persona if possible.
                    - Also make a note of customer's churn probaility predicted
                2. Recommended Actions:
                    - List the recommended actions based on the counterfactual analysis
                3. **Questionnaire for Agent**:
                    - Develop a set of questions for the customer service agent to ask customers to implement the recommended actions.
                """
        else:
            prompt = f"""

                You are an assistant to customer service manager who is looking for recommendations to reduce churn for a specific customer.
                You have access to major contributing factors towards churn across portfolio.
                Your goal is to provide clear and actionable insights on how to reduce customer churn based on available information and to develop effective questions to engage customers and implement the recommendations.
                Only make recommendations based of action features for a specific customer.
                Your task is as below:-

                    1. Read and Analyze the Data:
                        - Understand who the customer is. Focus on customer and contract features.
                            Below is the list of customer level feature names:
                            {self.conf['llm_subsets']['customer_features']}
                            Below is the list of customer contract feature names:
                            {self.conf['llm_subsets']['contract_features']}

                    2. Identify Key Insights:
                        
                        - Look and understand at the major contributing features towards churn across portfolio below 
                        - Understand what the current values of the customer are for these features
                        - Only make recommendations based of action features for a specific customer.
                        - Make recommendations to customer based on action features grounded by major contributing factors cross portfolio to reduce churn

                    3. Communicate Clearly:
                        - Use simple and clear language to explain the recommendations.
                        - Avoid technical jargon and ensure the explanation is understandable for a customer service agent.
                        - Support your findings with evidence from the SHAP summary with probability changes.

                    4. Provide Specific Recommendations:
                        - Only make recommendations based of action features for a specific customer.
                        - Detail the actions that can be taken to reduce churn.
                        - Explain why these actions are effective.
                        - Include examples or scenarios to illustrate the recommendations.

                    5. Create Questionnaires:
                        - Develop specific questions for customer service agents to ask customers in order to implement the recommended actions.
                        - Ensure the questions are relevant to the recommended actions and designed to gather necessary information or prompt customer engagement.
                        - Do not ask personal questions or questions about data already available to you.
                        - Questionnaire should be sequenced in a way that it helps to implement the recommendations.
                        - QUestionnaire should be designed in a way that it helps to understand the customer's current situation and how the recommendations can be implemented.
                        - Questionnaire should be sequential. The answer to one question should lead to the next question.
                        - Create multiple different segments of questions for each recommended action.


                Below is the major contributing factors towards churn across portfolio:
                ### Insights and Analysis:

                1. **Current Equipment Days**:
                - Customers with longer current equipment days (in the range of 1085.2 to 1630.3 days) have a significantly higher churn probability, with a probability change of 12.69% to 12.23% compared to the baseline model. This indicates that customers who have been using their equipment for a longer duration might be more likely to churn.

                2. **Percentage Change in Minutes**:
                - A significant negative change in minutes usage (in the range of -2061.6 to -1154.9) is strongly associated with higher churn probability, with a probability change of 13.03%. This suggests that customers who significantly reduce their minutes usage might be experiencing dissatisfaction and are more likely to churn.

                3. **Service City**:
                - Customers in "inh" and "slc" cities have the highest churn probability, with a probability change of 8.47% and 8.20%, respectively. This implies that there might be specific challenges or factors in these locations contributing to higher churn rates.

                4. **Revenue per Minute**:
                - Customers with higher revenue per minute (in the range of 44.65 to 61.59) have a higher churn probability, with a probability change of 11.29%. This could be linked to price sensitivity among high-revenue users or potential dissatisfaction with service quality.

                5. **Handset Refurbished**:
                - Customers who have refurbished handsets show a higher churn probability (probability change of 3.55%). This could indicate dissatisfaction with the quality of refurbished handsets or a perception of lower value compared to new devices.

                6. **Made Call to Retention Team**:
                - Customers who have contacted the retention team have a significantly higher churn probability (probability change of 10.18%). This indicates that these customers were likely already dissatisfied and seeking solutions before ultimately deciding to churn.

                Below is the customer details:
                {customer}

                Below is the list of action feature names:
                {self.conf['llm_subsets']['action_features']}



                Below is the original user question. Use it to identify the context of the report:
                {user_question}


                ***OUTPUT FORMAT SHOULD BE AS BELOW***:

                1. Customer Persona::
                    - Describe who the customer is in 30 words or less, including a persona if possible.
                    - Also make a note of customer's churn probaility predicted
                2. Recommended Actions:
                    - List the recommended actions based on the counterfactual analysis
                3. **Questionnaire for Agent**:
                    - Develop a set of questions for the customer service agent to ask customers to implement the recommended actions.

                """
        #print(prompt)
        recommendation = self.churnexplainer.generate_content(prompt, stream=False)
        return recommendation.candidates[0].content.parts[0].text