# .streamlit/config.toml

[theme]
primaryColor = "#d9d9d9"                  # Light grey for primary elements
backgroundColor = "#f0f0f0"               # Light grey background color
secondaryBackgroundColor = "#d3d3d3"
textColor = "#1a1a1a"                     # Dark grey text color for better visibility
font = "sans serif"                       # Font setting (optional)
